### ISSUE TITLE
prettyConjugation card type is too inflexible for only one language

### ISSUE THREAD

**Issue by BrucePlumb** [b3nj5m1n/moderncardthemes#1]
Very pretty indeed! But one small complaint. For different languages one would have to create different card types for each languages, changing the personal prepositions in the templates of each card to the new language. May I suggest adding 6 fields to hold the personal prepositions (formatted to tiny fonts so they don't intrude). The templates then just show that field e.g. {{sing1prep}}.
Which method is preferred is a personal choice, perhaps depending on how many languages you study.

**Comment by b3nj5m1n** [comment]
Hi, this was actually on my to-do list, but since I only really studied Spanish I never got to it. Since there's an interest now, I'll do it next.
I don't like the idea of having 6 extra fields, I'm currently planning on doing it by having one extra field containing all of the prepositions, either ; separated or as a json.

**Comment by b3nj5m1n** [comment]
I added this feature in dc1e0c7d323b86d3057adaf25a680b721645fe87.
