### ISSUE TITLE
Adding a second example sentence

### ISSUE THREAD

**Issue by ghost** [b3nj5m1n/moderncardthemes#4]
Hi, I was wondering if it was possible to add a second example sentence while doing flashcards, cause just one can be quite limited especially if the words can be placed differently with different contexts. 
Thank you 😊

**Comment by b3nj5m1n** [comment]
There isn't really a built-in way to do this, I would suggest either just putting each sentence on its own line, or modifying the card template yourself to allow for multiple sentences.

There's also the option of using the sentence card template.

**Comment by ghost** [comment]
1. I don't have the sentence card template, idk why maybe because of an import bug or something.
2. I don't have the knowledge to modify this type of card, and there's only one line for just one sentence, not two, and I would like a second line to be able to put a second sentence.

**Comment by b3nj5m1n** [comment]
> I don't have the sentence card template, idk why maybe because of an import bug or something.

Yeah, that checks out, I've had some problems with it myself. I'm not sure what exactly is causing it might be due to an issue where the deck is not properly exported. This is either a bug in CrowdAnki or because I'm missing something, likely the latter, but I haven't had the chance to look into it properly yet.

> I don't have the knowledge to modify this type of card,

A simple tutorial on YouTube would likely be enough for something like this.

> and there's only one line for just one sentence, not two, and I would like a second line to be able to put a second sentence.

Is there any problem with simply putting the second sentence on another line in the same field; is there any particular reason you need multiple fields for it?

**Comment by ghost** [comment]
Yes there's a problem, because I want two separate audios for 2 sentences and not 1 audio for 2 sentences. I don't get it, you're the creator of this template and you're not even able to modify,  I believe, this simple parameter for the sake of your users ? I'm sorry but it doesn't make sense, the user shouldn't be the one modifying your work it's just common sense, I made this request in order for you to make it, not me, I'm in the request tab, not in the "do it yourself" tab.

**Comment by b3nj5m1n** [comment]
> Yes there's a problem, because I want two separate audios for 2 sentences and not 1 audio for 2 sentences.

Makes sense, you could have led with that.

> I don't get it, you're the creator of this template and you're not even able to modify,

Of course I am

> I believe, this simple parameter for the sake of your users?

One user. You. I haven't heard from anyone else having this problem, so why would I make a change like this that unnecessarily overcomplicates the template for other users and requires maintenance and such if there's just one person getting use out of it?

> I'm sorry but it doesn't make sense, the user shouldn't be the one modifying your work

This is an open source project. It is **my** work. I made it for **me**. I chose to share my **work**, for **free**, so that others may get some use out of it. This doesn't mean I'll do whatever anyone asks me to do. This also doesn't mean I'll just jump to making changes without knowing exactly what the problem is. I mean, I didn't even say no, did I? I simply asked you to explain yourself, so I know exactly what the problem is, and we can find the best possible solution. On bigger projects a process like this can take years, but you don't have the patience to wait *a day*?

> I made this request in order for you to make it, not me, I'm in the request tab, not in the "do it yourself" tab.

Your audacity is honestly baffling. You're in the "hey I have a problem with something you provided yourself for free without any promise to maintain it or provide support, so please spend up to several hours of your time on a problem I have" tab.

Usually I go over the problem, and if it's something that everyone can get something out of, I do it. If I don't have the time, someone else might make a fork and a pull request. That's how open source works. If you don't have the (In this case honestly tiny) skill set to do something yourself, you ask the creator *nicely*, if they say no, you accept it, or your offer to pay them for their *work*.

Please use a more appropriate tone next time. I also won't do this, so I'll close this issue. Please do not re-open unless you have something meaningful to add.

**Comment by ghost** [comment]
Hey I'd like to apologize, I didn't mean to sound rude on my messages and I'm sorry if some of them were misunderstood or taken out of context. Thanks for your help, I truly appreciate all your effort for improving Anki's interface and I'll try to be more cautious next time.
